### ISSUE TITLE
Bug: Selecting "Select-All" option removes the earlier selected options.

### ISSUE THREAD

**Issue by Kamalashree-24** [hc-oss/react-multi-select-component#382]
Hi,
Thank you for your work. It is really a good library to use for dropdowns.

Currently facing an issue in this library, mentioned the use case below.
1. First user selects an option from the list.
2. Then the user searches for a specific string and dropdown filters out the options based on user search.
3. Now the user selects "select-all" option based on user search.
4. what happens is that user is left out with the last selected options, previously selected option is removed.

Desired behaviour:
The user should be able to select an option and even if he searches and click on "Select-all" option, the previously selected option should be retained unless user deselects it.

**Comment by harshzalavadiya** [comment]
Thanks for the report I'll try to fix in a few days, but PRs are always welcomed 🙂

**Comment by harshzalavadiya** [comment]
this bug was fixed earlier now it retains existing selection when choosing select-all in filtered view
