### ISSUE TITLE
dropdown width keeps increasing with more elements selected

### ISSUE THREAD

**Issue by nitish2507** [hc-oss/react-multi-select-component#440]
the dropdowns keep expanding with more items selected and it's breaking the UI.
looking for suggestions on how to override the CSS to achieve this as we don't see any available props for it.

**Comment by harshzalavadiya** [comment]
@nitish2507 Please provide reproduction codesandbox if you have any issues

most components have standerd classes attached to it you can override classes in your choice of framework by targeting that class

**Comment by harshzalavadiya** [comment]
closing due to no response
