### ISSUE TITLE
Remote load

### ISSUE THREAD

**Issue by cubecleveland** [hc-oss/react-multi-select-component#453]
hi,

sorry for posting here but is there any way to use remote load and serach on this componenet ?

**Comment by harshzalavadiya** [comment]
@cubecleveland Yes It's possible.

I have created a small example you can modify it as per your needs

[![Edit rmsc-filter-options-async](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rmsc-filter-options-async-0gk39?fontsize=14&hidenavigation=1&theme=dark)

```jsx
import React, { useState } from "react";
import MultiSelect from "react-multi-select-component";
import "./styles.css";

export default function App() {
  const options = [];
  const [selected, setSelected] = useState([]);

  // Custom function that overrides filtering logic
  const filterOptions = async (options, filter) => {
    if (filter) {
      // Fetch data from REST API
      const data = await fetch(`https://swapi.dev/api/people/?search=${filter}`).then((o) => o.json());

      // Remodal response it to fit with component
      return data?.results?.map((person) => ({
        label: person.name,
        value: person.name
      }));
    }

    // by default return current selection
    return selected;
  };

  return (
    <div>
      <h1>Search Star wars people (for example "r2-d2")</h1>
      <pre>{JSON.stringify(selected)}</pre>
      <MultiSelect
        options={options}
        value={selected}
        onChange={setSelected}
        filterOptions={filterOptions} // <-
        labelledBy={"Select"}
      />
    </div>
  );
}
```

**Comment by cubecleveland** [comment]
This is uperb. Im sure you already did this before so ill go ahead and asked.. any chance to send an example that will be debounced and not shoot thew api on every keystroke..  maybe every 1000ms ?

Thanks a bunch!

**Comment by harshzalavadiya** [comment]
@cubecleveland this is built in simply use prop `debounceDuration` (in ms 2000 means 2 seconds)
![image](https://user-images.githubusercontent.com/5774849/129567505-012188db-a73e-4c71-8bab-19adeda69298.png)

**Comment by cubecleveland** [comment]
Absolutely wonderful. and its exactly what i need i have 2 questions. can i
show the component already open with the first alue from async already
loaded. also can i always leave it open ? (so basically the combos
stais open all the time)


CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629

**Comment by harshzalavadiya** [comment]
@cubecleveland pre-loaded/pre-selected should work as is, controlling open state/always open is not available
