### ISSUE TITLE
Focus select

### ISSUE THREAD

**Issue by macielgaleano** [hc-oss/react-multi-select-component#466]
Hello! 

I have a question... the library support take out the focus? 
If so, can you tell me how

Thanks for the support, keep in that way!

**Comment by harshzalavadiya** [comment]
@macielgaleano I don't get your question, do you mean by onBlur event like any other element, or you just want to style it when out of focus?

**Comment by macielgaleano** [comment]
@harshzalavadiya 

I have already found what i wanted.

Thanks you.

**Comment by abish373** [comment]
How you solves the issue @macielgaleano. 

Here is what I need
 If user don't select any of the option need to focus at onSubmit event
