### ISSUE TITLE
does anyone have import issue for 4.1.5? 

### ISSUE THREAD

**Issue by bruceoh-rtm** [hc-oss/react-multi-select-component#467]
I am having import issue with typescript. 

wondering if anyone is having same problem.

import  {MultiSelect}  from "react-multi-select-component";
Cannot find module 'react-multi-select-component' or its corresponding type declarations.

**Comment by harshzalavadiya** [comment]
@bruceoh-rtm can you provide more information?

is it CRA/Next.js ?
TypeScript/JS ?

**Comment by harshzalavadiya** [comment]
@bruceoh-rtm I was able to isolate issue, due to move from `tsdx` to `microbundle` TS typings reference was missing and so production build w/ CRA + TS was failing

update to `v4.1.6` to fix this issue

closing this for now, feel free to re-open if you are still having issues

**Comment by harshzalavadiya** [comment]
reopening this there's some wierd bug w/ microbundle

**Comment by harshzalavadiya** [comment]
fixed in `v4.1.8`
