### ISSUE TITLE
JSX element type 'MultiSelect' does not have any construct or call signatures

### ISSUE THREAD

**Issue by sharpk1** [hc-oss/react-multi-select-component#468]
Has anyone using TypeScript in their project ever seen something like this? Here is the full error:
```

#19 126.6     TSError: TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
#19 126.6     src/modules/project/agent/components/agents/filters/DropdownFilter.tsx:46:14 - error TS2604: JSX element type 'MultiSelect' does not have any construct or call signatures.
#19 126.6
#19 126.6     46             <MultiSelect
#19 126.6                     ~~~~~~~~~~~

```

This error gets thrown whenever I try to docker build or it hits the Jenkins build pipeline. The component itself runs just fine. Any help would be greatly appreciated!

**Comment by harshzalavadiya** [comment]
@sharpk1 If possible can you provide minimal reproduction?,
most probably node version/ts version might be an issue, try to match the same and should work as is...

**Comment by sharpk1** [comment]
@harshzalavadiya  No worries, I ended up npm uninstalling and then npm installing with --force. There was some sort of discrepancy in versions and it not showing up with my linter. I ended up adding brackets around the import statement like so and it works just fine now: `import { MultiSelect } from 'react-multi-select-component';`
