### ISSUE TITLE
Remove focus on first element if disableSearch is set to true

### ISSUE THREAD

**Issue by PierrickG1** [hc-oss/react-multi-select-component#477]
Hi,

I would like to report a bug on the drop down menu if you disable the search, the first element has the background focused by default.
It is possible to disable this focus on the first element if search is disabled ? 
Reproduction sandbox : https://codesandbox.io/s/awesome-haze-zbsdx?file=/src/App.js

version used: 4.1.8

Thanks :)

**Comment by harshzalavadiya** [comment]
@PierrickG1 If search is disabled it's suppose to automatically focused on next available element so it will make it easy for screen readers any specific reason on why this should not happen?

**Comment by harshzalavadiya** [comment]
closing this due to no response
