### ISSUE TITLE
bug in package.json

### ISSUE THREAD

**Issue by rfb** [hc-oss/react-multi-select-component#478]
Just attempted to add react-multi-select-component to a create-react-app project. Met with this error:

```
src/components/EditArtistModal/index.tsx
  Line 29:29:  Unable to resolve path to module 'react-multi-select-component'  import/no-unresolved
```

Did a quick look in `node_modules/react-multi-select-component/package.json` and I see that `main` is a file that doesn't exist: `./dist/react-multi-select-component.cjs.js`. 

If I change `main` to `./dist/react-multi-select-component.cjs` the app compiles.

**Comment by harshzalavadiya** [comment]
@rfb my bad I was trying out something and accidently published canary package please try now

**Comment by rfb** [comment]
👍 looks good, thank you for publishing this library!
