### ISSUE TITLE
Add custom props to change wording in placeholders (select, search textbox)

### ISSUE THREAD

**Issue by charlo-chopin** [hc-oss/react-multi-select-component#482]
Its seems there is no way to customize the placeholder "Select..." and "Search".
It could be nice for multi language websites : )

**Comment by harshzalavadiya** [comment]
@charlo-chopin its already there

https://github.com/hc-oss/react-multi-select-component/blob/master/docs/recipes/localization.md

**Comment by charlo-chopin** [comment]
Great thank you!
