### ISSUE TITLE
Issues with Select all and filter options in 4.1.13

### ISSUE THREAD

**Issue by anilkumarmr** [hc-oss/react-multi-select-component#499]
I found 2 issues with the component
   1)Filter option is executing everytime the option is selected which is not ideal.
     Especially while performing async calls, because it will cause multiple api calls eventhough the search text is not changed
   2)Select all is not selecting all the available options [codesandbox](https://codesandbox.io/s/peaceful-kapitsa-c6ct5-c6ct5)

**Comment by anilkumarmr** [comment]
Any updates on the issues?

**Comment by harshzalavadiya** [comment]
@anilkumarmr thanks for reporting this but this could take a while since I don't have much time to work on this due to personal reasons but PR is always welcome :)
