### ISSUE TITLE
Dropdown overflows in column grid 

### ISSUE THREAD

**Issue by pewax** [hc-oss/react-multi-select-component#509]
The problem is: 
I require multiple Multiselect components side by side, column-wise. However, when adding two or more Multiselect components inside a flexbox div, the dropdown item list will keep expanding when selecting more elements and then overflow.

 https://codesandbox.io/s/gallant-shape-35xzz?file=/src/App.js

**Comment by harshzalavadiya** [comment]
@pewax I don;t get this fully

*if you mean by elipsis (...) instead of overflow?*
in this case you can use custom renderer or override css to go multiline

*or do you mean that textboxes are resizing itself?*
in this case you can use grid layout instead of flex box

**Comment by pewax** [comment]
I went with grid instead of flex. It solved the problem.
