### ISSUE TITLE
Enhancement: isCreatable

### ISSUE THREAD

**Issue by romseguy** [hc-oss/react-multi-select-component#510]
Hello, how about allowing to override `Create "string"` ? Let's add `"createItem"` in https://github.com/hc-oss/react-multi-select-component/blob/HEAD/docs/recipes/localization.md ? Thank you

edit: also when `options` is an empty object it'd be nice if we wouldn't be offered to create an empty item:

![Selection_003](https://user-images.githubusercontent.com/109238/141316666-14034418-ed58-4ca4-8a15-29a025b97aa3.png)

**Comment by harshzalavadiya** [comment]
@romseguy It was [already there](https://github.com/hc-oss/react-multi-select-component/blob/7949a0ab64e31a6de17b7a057f8b3e8a4ed2e04e/src/hooks/use-multi-select.tsx#L15) I have updated documentation
