### ISSUE TITLE
Feature request: isOpen prop

### ISSUE THREAD

**Issue by romseguy** [hc-oss/react-multi-select-component#511]
Hello, it'd be nice for development purposes to have `isOpen` prop so we can force the dropdown open. Thanks!

**Comment by harshzalavadiya** [comment]
@romseguy there's already an `defaultIsOpen` prop

but easy way to do this (and should work everywhere) might be you can use chrome's built-in *emulate a focused page* feature can be accessed from 

inspect element &rarr; `ctrl + shift + p` &rarr; type "emulate a focused page"

that should prevent it from closing while in development
![image](https://user-images.githubusercontent.com/5774849/141421736-bf09c19c-f99f-4b8b-95ac-8ad1e5f2a016.png)
