### ISSUE TITLE
custom list item - with image

### ISSUE THREAD

**Issue by muh-hizbe** [hc-oss/react-multi-select-component#513]
I was custom item list, but i'll the image not rendered at **select all** option.

code can reproduce at [https://codesandbox.io/s/custom-checkbox-multi-select-with-image-5ielk](https://codesandbox.io/s/custom-checkbox-multi-select-with-image-5ielk)

**Comment by harshzalavadiya** [comment]
@muh-hizbe you can just do a falsy value check, `Select All` value will be empty

here's updated version link https://codesandbox.io/s/custom-checkbox-multi-select-with-image-forked-dn9hb
