### ISSUE TITLE
Multilingual support - search does not work with Hebrew 

### ISSUE THREAD

**Issue by aviraminy** [hc-oss/react-multi-select-component#542]
I have an options which some of them are in English and some are in Hebrew.
When i try to filter in Hebrew nothing happens

**Comment by harshzalavadiya** [comment]
@aviraminy can you provide codesandbox?

**Comment by jung0han** [comment]
In Korean, it does not work the same.
[https://codesandbox.io/s/cool-elgamal-qnjy47](url)
![Hnet com-image-2](https://user-images.githubusercontent.com/27123002/158008851-5ab2a902-52ee-4701-95a1-08fa096e8c2b.gif)

**Comment by harshzalavadiya** [comment]
Thanks for reproduction I'll take a look
