### ISSUE TITLE
Selected values customization

### ISSUE THREAD

**Issue by splendidlom** [hc-oss/react-multi-select-component#552]
Hi. Thank you for your work!

Can you add selected values customization, please.
For example. Instead of selected values `Luke Skywalker, C-3PO` I want to set custom lable like `2 selected`

![image](https://user-images.githubusercontent.com/31928196/152356594-71e6dd99-c5fb-4e10-b477-2a3716f3c872.png)

**Comment by harshzalavadiya** [comment]
@splendidlom It's already there. please use `valueRenderer` prop

https://react-multi-select-component.pages.dev/?path=/story/recipes-custom-value-renderer--page
