### ISSUE TITLE
Option Alignment in the Menu is all Wonky

### ISSUE THREAD

**Issue by zanewolf** [hc-oss/react-multi-select-component#553]
**Describe the bug**
I've implemented the multiselect component into my map and added the options. However, regardless of whether the component is on the left or right side of the page, the options are poorly formatted and I'm not sure what is causing this or how to fix it. 

![image](https://user-images.githubusercontent.com/30910417/153511745-298101dc-9186-4e75-9087-9fcc7c7a7ad3.png)

![image](https://user-images.githubusercontent.com/30910417/153511810-34014143-41b5-4118-b21d-90dc1e468a1e.png)

Any thoughts?

**Comment by harshzalavadiya** [comment]
@zanewolf this looks like some global styling conflict issue, if you can reproduce sandbox I can probably help you reset styles
