### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by devdreamsolution** [hc-oss/react-multi-select-component#557]
I wanted to read about the customization, but the link was existed.
Check this screenshot.

![image](https://user-images.githubusercontent.com/54434088/155561710-85bd8a84-4154-4d55-9eb8-41e541e2aaf0.png)

**Comment by harshzalavadiya** [comment]
@devdreamsolution Thanks for notifying I'll update them in next release,

Meanwhile you can use docs: https://react-multi-select-component.pages.dev/

**Comment by devdreamsolution** [comment]
OK, Thank you.

**Comment by harshzalavadiya** [comment]
@devdreamsolution README.md is updated new documentation will be available on NPM in few minutes

**Comment by devdreamsolution** [comment]
Thank you, @harshzalavadiya
