### ISSUE TITLE
Optional Clear Button

### ISSUE THREAD

**Issue by makapiatia** [hc-oss/react-multi-select-component#577]
I like how lightweight your multi select component is, the only additional functionality I would like to see is the option to remove the clear button that appears when selections are made. It seems like a simple capability to add, I would be happy to update the project with this feature.

**Comment by makapiatia** [comment]
I must have missed this, I see now that setting "ClearSelectedIcon={<></>}" will do just this.

**Comment by nickmcmillan** [comment]
Using `ClearSelectedIcon={<></>}` still results in a "Clear Selected" button being added to the DOM, but with no child elements. This might look fine, but it's no good for keyboard accessibility. Users can still tab to the button but will get no visual indication of it.

It'd be better if we could completely opt out of the clear button.

**Comment by harshzalavadiya** [comment]
@nickmcmillan I guess you are right I'll see if we can just remove it completely

**Comment by harshzalavadiya** [comment]
@nickmcmillan README.md is updated new documentation will be available on NPM in few minutes

**Comment by harshzalavadiya** [comment]
@nickmcmillan have pushed new update updates will be available in few minutes
