### ISSUE TITLE
It should be clear which select-item is the current index

### ISSUE THREAD

**Issue by MegaKeegMan** [hc-oss/react-multi-select-component#594]
## The problem
An item selection is indicated by a checkbox, as well as a darker gray background. The current index is displayed as a slightly lighter gray background. When your index is on the already selected items, there is practically no visual queue (that I have noticed) to indicate which item you are on in the tab order.

Here is an example: 
![multi-select-index-issue](https://user-images.githubusercontent.com/81833462/170771501-ad6e7227-a35a-4b8f-911f-331a6966b244.png)
I have just created a new entry, and my attention is most drawn to this gray background on the selected item. As a first time user, I expect that that gray background is my location in the tab order. Someone with keener eyes might notice the cursor in the search bar, but not me. So I am about to be pretty confused when I hit the down arrow and "Select All" gets a light gray background, rather than "Grapes :grapes: ". It is similarly confusing when the "Select All" option is disabled, and there would be even less visual queue that anything even happened when I press the down arrow.

## Proposed solution
This doesn't 100% fix the problem I have mentioned, but it would help a lot if the current index was indicated by a colored border around the select-item. The light gray background can stay, too.

**Comment by harshzalavadiya** [comment]
I just restored browser focus ring back with few adjestments for now so it makes things simple
