### ISSUE TITLE
Lost access to ISelectProps after bumping versions

### ISSUE THREAD

**Issue by afmfe-iul** [hc-oss/react-multi-select-component#630]
**Is your feature request related to a problem? Please describe.**
After upgrading from version `4.1.12` to version `4.3.2` we lost access  to `ISelectProps`, prior we were importing it from `react-multi-select-component/dist/types/lib/interfaces`.

**Describe the solution you'd like**
`ISelectProps` would be accessible again.

**Describe alternatives you've considered**
We made a copy of `ISelectProps` on our project.

Edit:
Also lost access to the `Option` interface.

**Comment by harshzalavadiya** [comment]
@afmfe-iul Thanks for reporting this.

I've restored TypeScript types back and can be directly imported like below

```tsx
import { MultiSelect, SelectProps, Option } from "react-multi-select-component";
```

**Comment by afmfe-iul** [comment]
Thanks for the quick action @harshzalavadiya, much appreciated! :)
