### ISSUE TITLE
is there any callback function for onClose dropdown? I want to call server request after selecting items. I don't want to call server request for each change

### ISSUE THREAD

**Issue by nageshweb8** [hc-oss/react-multi-select-component#635]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshzalavadiya** [comment]
@nageshweb8  I think you are looking for `onMenuToggle` sends `true` and `false` each time dropdown toggles
