### ISSUE TITLE
Option to add placeholder when no option is selected

### ISSUE THREAD

**Issue by murtazamehmudji** [hc-oss/react-multi-select-component#645]
There should be a prop passed to the component to show a placeholder when no option is selected. Right now it shows **Select...**

**Comment by harshzalavadiya** [comment]
@murtazamehmudji you can easily customize `select...` for accessiblity there's already aria-label provided so that should do the job

https://github.com/hc-oss/react-multi-select-component/blob/master/stories/recipes/localization.stories.mdx

**Comment by tg-murtaza** [comment]
@harshzalavadiya This is not about internationalization. Even after passing the labelledBy prop the placeholder still remains to be Select...

**Comment by murtazamehmudji** [comment]
@harshzalavadiya  This is not about internationalization. Even after passing the labelledBy prop the placeholder still remains to be Select...

**Comment by harshzalavadiya** [comment]
@murtazamehmudji It's not just localization the prop is called `overrideStrings` localization was just example.

please look at below sandbox which achieves the result you desire.

https://codesandbox.io/s/infallible-burnell-9k718n?file=/src/App.js
