### ISSUE TITLE
Can we get array from mulselect component?

### ISSUE THREAD

**Issue by ghulamyazdani** [hc-oss/react-multi-select-component#646]
**Is your feature request related to a problem? Please describe.**
Right now we are getting the whole object when we select an option, just wanted to ask if we can get array of selected options. if not can we add this feature?

current version has this -
![image](https://user-images.githubusercontent.com/55938346/192973472-d43f9ec5-98b1-4378-a4e8-d0dab3990d2c.png) - 
want this
![image](https://user-images.githubusercontent.com/55938346/192973602-07da623e-4e3d-4553-915e-d8602dbf24da.png)

**Comment by harshzalavadiya** [comment]
@ghulamyazdani 

you should be able to easily do it like below

```
const selectedValues = useMemo(() => {
  return selected.map((s) => s.value);
}, [selected]);
```

here's sandbox sample

https://codesandbox.io/s/nostalgic-bush-pvv4zz?file=/src/App.js:679-778

> as of now there are no plans/bandwith for me to support this is just extra maintainablity plus increases bundle size similar results can be easily achieved using little bit of code
